/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tienda;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class NuevoProveedor extends javax.swing.JFrame {

    public Connection con;
    
    public NuevoProveedor() {
        initComponents();
        Conectar();
        CargarDatos();
        txtId.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNuevoProveedor = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaDatos = new javax.swing.JTable();
        txtId = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtProveedor = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(688, 333));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        txtNuevoProveedor.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtNuevoProveedor.setText("NUEVO PROVEEDOR");

        txtTitulo.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtTitulo.setText("LISTA DE  PROVEEDORES");

        jTablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablaDatos);

        txtId.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID DEL PROVEEDOR:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12))); // NOI18N

        btnGuardar.setBackground(new java.awt.Color(28, 109, 66));
        btnGuardar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blanco.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(76, 8, 8));
        btnEliminar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bin.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtProveedor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NOMBRE DEL PROVEEDOR:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtNuevoProveedor)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(txtTitulo)
                        .addGap(101, 101, 101))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNuevoProveedor)
                        .addGap(18, 18, 18)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaDatosMouseClicked
        // Si da click en un registro, los datos de ese registro (el nombre del proveedor) se muestra en la caja de texto:
        String id = jTablaDatos.getValueAt(jTablaDatos.getSelectedRow(), 0).toString();
        String nombre = jTablaDatos.getValueAt(jTablaDatos.getSelectedRow(), 1).toString();
        txtId.setText(id);
        txtProveedor.setText(nombre);
    }//GEN-LAST:event_jTablaDatosMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (!(("".equals(txtId.getText())))) {
            try {
                String proveedor = txtId.getText();

                PreparedStatement ptmInsert = con.prepareStatement("INSERT INTO tbl_proveedor(nombreproveedor) VALUES(?)");
                ptmInsert.setString(1, proveedor);

                int respuesta = ptmInsert.executeUpdate();

                if (respuesta > 0) {
                    JOptionPane.showMessageDialog(null, "EL REGISTRO FUE AGREGADO EXITOSAMENTE.","EXITO.", JOptionPane.INFORMATION_MESSAGE);
                    CargarDatos();
                }
                else{
                    JOptionPane.showMessageDialog(null, "PARECE QUE OCURRIO UN ERROR AL AGREGAR EL REGISTRO.","ERROR.", JOptionPane.ERROR_MESSAGE);
                }

            } catch (SQLException ex) {
                //Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Error: " + ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "ASEGURESE DE HABER LLENADO COMPLETMENTE EL FORMULARIO.","ERROR.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // Elimina el proveedor seleccionado en la tabla
        if (!("".equals(txtId.getText()))) {
            int verificar = JOptionPane.showConfirmDialog(null, "¿ESTA SEGURO QUE DESEA ELIMINAR EL REGISTRO?", "CONFIRME.", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (verificar == JOptionPane.YES_OPTION) {
                try {
                    int id = Integer.parseInt(txtId.getText());
                    PreparedStatement ptmElim = con.prepareStatement("DELETE FROM tbl_proveedor WHERE idproveedor = ?");
                    ptmElim.setInt(1, id);
                    
                    int respuesta = ptmElim.executeUpdate();//Retorna la cantidad de registros afectados 
                    
                    if (respuesta > 0) {
                        JOptionPane.showMessageDialog(null, "EL REGISTRO FUE ELIMINADO EXITOSAMENTE.","EXITO.", JOptionPane.INFORMATION_MESSAGE);
                        CargarDatos();
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "PARECE QUE OCURRIO UN ERROR AL ELIMINAR EL REGISTRO.","ERROR.", JOptionPane.ERROR);
                    }
                } catch (SQLException ex) {
                    //Logger.getLogger(NuevoProveedor.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "PARECE QUE OCURRIO UN ERROR AL ELIMINAR EL REGISTRO.","ERROR.", JOptionPane.ERROR);
                    System.out.println("Excepcion -> " + ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "POR FAVOR, ASEGURESE DE HABER SELECCIONADO EL REGISTRO QUE DESEA ELIMINAR.","ERROR.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        txtId.setText("");
        txtProveedor.setText("");
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoProveedor().setVisible(true);
            }
        });
    }
    
    public void Conectar(){
        //Accede a la base de datos donde se aloja toda la información
        String url = "jdbc:postgresql://localhost:5432/db_tienda";//La base de datos se maneja de manera local en el puerto 5432 de PostgreSQL
        try {
            //*************************************************************************************************************************************************
                                            //"url", "user", "password"
            con= DriverManager.getConnection(url,"postgres", "S4mu3lcoc#27");//<- **************** AQUI VA SU CONTRASEÑA **************************************
            //*************************************************************************************************************************************************
            System.out.println("EL FORMULARIO SECUNDARIO SE HA CONECATADO A LA BASE DE DATOS");
        } catch (SQLException ex) {
            //Logger.getLogger(ConexioDB_CLASE.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("ERROR AL REALIZAR LA CONEXION -> "+ex);
        }  
    }
    
    public void CargarDatos(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo = (DefaultTableModel)jTablaDatos.getModel();
        modelo.setRowCount(0);//Limpia todas los registros de la tabla (Basicamente le indica que no quiere ninguna fila)
        
        try {
            Statement smt = con.createStatement();
            String consulta = "SELECT * FROM tbl_proveedor";
            ResultSet resultado = smt.executeQuery(consulta);
            while(resultado.next()){
                modelo.addRow(new Object[]{resultado.getInt("idproveedor"),resultado.getString("nombreproveedor")});
            }
            jTablaDatos.setModel(modelo);
        } catch (SQLException ex) {
            //Logger.getLogger(ConexioDB_CLASE.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("ERROR AL EJECUTAR LA CONSULTA ->"+ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaDatos;
    private javax.swing.JTextField txtId;
    private javax.swing.JLabel txtNuevoProveedor;
    private javax.swing.JTextField txtProveedor;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
